-- begin WBNREPORTS_AZIENDA
alter table WBNREPORTS_AZIENDA add constraint FK_WBNREPORTS_AZIENDA_ON_FIRMA_TITOLARE_PRIVACY foreign key (FIRMA_TITOLARE_PRIVACY_ID) references SYS_FILE(ID)^
alter table WBNREPORTS_AZIENDA add constraint FK_WBNREPORTS_AZIENDA_ON_ID_LOGO foreign key (ID_LOGO) references SYS_FILE(ID)^
create index IDX_WBNREPORTS_AZIENDA_ON_FIRMA_TITOLARE_PRIVACY on WBNREPORTS_AZIENDA (FIRMA_TITOLARE_PRIVACY_ID)^
create index IDX_WBNREPORTS_AZIENDA_ON_ID_LOGO on WBNREPORTS_AZIENDA (ID_LOGO)^
-- end WBNREPORTS_AZIENDA
-- begin WBNREPORTS_CLIENTE
alter table WBNREPORTS_CLIENTE add constraint FK_WBNREPORTS_CLIENTE_ON_AZIENDA foreign key (AZIENDA_ID) references WBNREPORTS_AZIENDA(ID)^
create index IDX_WBNREPORTS_CLIENTE_ON_AZIENDA on WBNREPORTS_CLIENTE (AZIENDA_ID)^
-- end WBNREPORTS_CLIENTE
